version: '3.8'

services:
 app:
  restart: always
  build: ./api
  command: /app/main
  ports:
   - 8000:8000
  depends_on:
   - db
   - migrate
  environment:
   - DB_PASSWORD=postgres

 migrate:
  image: arigaio/atlas:latest
  command: >
   migrate apply 1
   --url "postgresql://postgres:postgres@db:5432/postgres?search_path=public&sslmode=disable"

  depends_on:
   - db
  volumes:
   - ./db/postgresql/migrations/:/migrations


 db:
  restart: always
  image: postgres:latest
  volumes:
   - ./db/postgresql/.database/postgres/data:/var/lib/postgresql/data
  environment:
   - POSTGRES_PASSWORD=postgres
   - POSTGRES_USER=postgres
  ports:
   - 5436:5432



