version: '3.8'

services:
 app:
  ports:
   - "8000:8000"
  restart: always
  build: ./api
  command: /app/main
  depends_on:
   - db
   - migrate
   - kafka
  environment:
   - DB_PASSWORD=postgres

 migrate:
  image: arigaio/atlas:latest
  command: >
   migrate apply 1
   --url "postgresql://postgres:postgres@db:5432/postgres?search_path=public&sslmode=disable"

  depends_on:
   - db
  volumes:
   - ./db/postgresql/migrations/:/migrations


 db:
  restart: always
  image: postgres:latest
  volumes:
   - ./db/postgresql/.database/postgres/data:/var/lib/postgresql/data
  environment:
   - POSTGRES_PASSWORD=postgres
   - POSTGRES_USER=postgres
  ports:
   - 5436:5432

 image:
  build: ./imageGeneration
  depends_on:
   - kafka

 kafka:
  image: confluentinc/cp-kafka:latest
  ports:
   - 29092:29092
  expose:
   - 9092
  environment:
   KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
   KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
   KAFKA_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://0.0.0.0:29092
   KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092"
   KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  depends_on:
   - zookeeper

 zookeeper:
  image: zookeeper
  ports:
   - "2181:2181"


