{
 "title": "Dashboard",
 "time": { "from": "now-10s", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(api_requests_total{endpoint!=\"/prometheus/metrics\"}[2s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Response latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "avg(rate(api_request_duration_seconds_sum{endpoint!=\"/prometheus/metrics\"}[2s])) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}